<?php
/**
* SMSFunnel | fieldset.phtml
* @category SMSFunnel
* @copyright Copyright (c) 2024 SMSFUNNEL - Magento Solution Partner.
* @author SMSFunnel
* @Support Leonardo Menezes - suporte@smsfunnel.com.br
 */
$customerData = $block->getCustomerData();
$phone = $customerData["phone"] ?? "";

?>
<legend class="legend"><span>Additional Information</span></legend>
<div class="field phone required">
    <label class="label" for="phone">
        <span><?= /** @noEscape */ __('Phone');?></span>
    </label>
    <div class="control">
        <input type="text" name="phone" id="phone"
               title="<?= /** @noEscape */ __('Phone');?>"
               class="input-text required-entry"
               maxlength="12"
               value="<?= /* @noEscape */ $phone ?>"
               data-validate="{required:true}"
               required>
    </div>
</div>
